apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  labels:
    app.kubernetes.io/name: nginx-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-app
    spec:
      containers:
      - name: myapp-nginx
        image: destian1995/nginx-app:1.0.0
        resources:
          requests:
            memory: "24Mi"
            cpu: "32m"
          limits:
            memory: "48Mi"
            cpu: "64m"
        ports:
        - containerPort: 80